
name: Build & Submit (EAS)

on:
  workflow_dispatch:
    inputs:
      platform:
        description: "ios | android | all"
        required: true
        default: "ios"
      profile:
        description: "eas profile (development | preview | production)"
        required: true
        default: "production"

jobs:
  build-submit:
    runs-on: ubuntu-latest
    env:
      EAS_TOKEN: ${{ secrets.EAS_TOKEN }}
      APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      ASC_APP_ID: ${{ secrets.ASC_APP_ID }}
      GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm i -g eas-cli expo-cli
- name: Install deps
  run: |
    npm config set fund false
    npm config set audit false
    if [ -f package-lock.json ]; then
      npm ci --legacy-peer-deps
    else
      npm install --legacy-peer-deps
    fi
      - name: Decode App Store Connect API key
        if: ${{ inputs.platform == 'ios' || inputs.platform == 'all' }}
        run: echo "$APP_STORE_CONNECT_PRIVATE_KEY" | base64 -d > asc_key.p8
      - name: Decode Google Play service account key
        if: ${{ inputs.platform == 'android' || inputs.platform == 'all' }}
        run: echo "$GOOGLE_SERVICE_ACCOUNT_JSON" | base64 -d > google-service-account.json
      - name: Build (EAS)
        run: |
          set -e
          PLATFORM="${{ inputs.platform }}"
          PROFILE="${{ inputs.profile }}"
          if [ "$PLATFORM" = "ios" ]; then
            eas build --platform ios --profile "$PROFILE" --non-interactive
          elif [ "$PLATFORM" = "android" ]; then
            eas build --platform android --profile "$PROFILE" --non-interactive
          else
            eas build --platform ios --profile "$PROFILE" --non-interactive
            eas build --platform android --profile "$PROFILE" --non-interactive
          fi
      - name: Submit to App Store Connect
        if: ${{ inputs.platform == 'ios' || inputs.platform == 'all' }}
        run: |
          set -e
          eas submit -p ios --latest             --asc-api-key-path asc_key.p8             --asc-api-key-issuer-id "$APP_STORE_CONNECT_ISSUER_ID"             --asc-api-key-id "$APP_STORE_CONNECT_KEY_ID"             --apple-team-id "$APPLE_TEAM_ID"             --app-identifier "com.jm.moodjournal"             --non-interactive
      - name: Submit to Google Play
        if: ${{ inputs.platform == 'android' || inputs.platform == 'all' }}
        run: |
          set -e
          eas submit -p android --latest             --key-file google-service-account.json             --non-interactive
